accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from books import views as book_views
from . import views

urlpatterns = [
    path('', book_views.IndexView.as_view(), name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name="register"),
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('book/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('book/new/', views.new_book, name='new_book'),
    path('book/<int:book_id>/delete', views.delete_book, name='delete_book'),
    path('book/<int:book_id>/edit_book', views.update_book, name='update_book'),
    path('book/<int:book_id>/edit_review', views.update_review, name='update_review'),
    path('books/search/', views.SearchResultsView.as_view(), name='results'),
    path('books/browse/by_<str:order_by>', views.BrowseView.as_view(), name='order_by')
]

librarti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('books.urls')),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    number = models.CharField(max_length=255, blank=True, null=True)
    price = models.TextField(blank=True, null=True)
    read_date = models.CharField(max_length=255, blank=True, null=True)
    add_date = models.DateTimeField('date added')
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

class Review(models.Model):
    NO_STARS = '☆☆☆☆☆'
    ONE_STAR = '★☆☆☆☆'
    TWO_STARS = '★★☆☆☆'
    THREE_STARS = '★★★☆☆'
    FOUR_STARS = '★★★★☆'
    FIVE_STARS = '★★★★★'
    REVIEW_CHOICES = [
        (NO_STARS, 'No stars'),
        (ONE_STAR, 'One star'),
        (TWO_STARS, 'Two stars'),
        (THREE_STARS, 'Three stars'),
        (FOUR_STARS, 'Four stars'),
        (FIVE_STARS, 'Five stars')
    ]
    book = models.OneToOneField(
        Book,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    stars = models.CharField(max_length=255, choices=REVIEW_CHOICES, default=NO_STARS)
    thoughts = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.stars

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

books/forms.py
from django.forms import Form, ModelForm, TextInput, Textarea, Select
from .models import Book, Review

class BookForm(ModelForm):

    class Meta:
        model = Book
        fields = ("name", "company", "number", "price")
        widgets = {
            "name": TextInput(attrs={'class': 'form-control'}),
            "company": TextInput(attrs={'class': 'form-control'}),
            "number": TextInput(attrs={'class': 'form-control'}),
            "price": Textarea(attrs={'class': 'form-control'})
            }

class ReviewForm(ModelForm):

    class Meta:
        model = Review
        fields = ('stars', 'thoughts')
        widgets = {
            'thoughts': Textarea(attrs={'class': 'form-control'})
        }

class StarForm(ModelForm):

    class Meta:
        model = Review
        fields = ('stars',)
        labels = {
            'stars': 'by Review',
        }
        widgets = {
            'stars': Select(attrs={'class': 'search-form'})
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm


# Create your views here.
def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save() 

        return redirect("/")
    else:
        form = RegisterForm()

    return render(response, "registration/register.html", { "form" : form })

books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Book, Review
from .forms import BookForm, ReviewForm, StarForm

# Create your views here.
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'books/book_view.html'
    context_object_name = 'books_list'

    def get_queryset(self):
        """Return the last five books according to add date"""
        return Book.objects.filter(user__id=self.request.user.id).order_by('-add_date')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = StarForm()
        return context

class BrowseView(generic.ListView):
    template_name = 'books/browse.html'
    context_object_name = 'ordered_books'

    def get_queryset(self):
        order_by = self.kwargs['order_by']
        if order_by == 'stars':
            return Book.objects.filter(user__id=self.request.user.id).order_by('review__stars')
        else:
            return Book.objects.order_by(order_by)

class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'

class SearchResultsView(generic.ListView):
    book_model = Book
    template_name = 'books/search_results.html'
    context_object_name = 'search_results'

    def get_queryset(self):
        if 'name' in self.request.GET:
            query = self.request.GET.get('name')
            return Book.objects.filter(user__id=self.request.user.id, name__icontains=query)


        elif 'company' in self.request.GET:
            query = self.request.GET.get('company')
            return Book.objects.filter(user__id=self.request.user.id, company__icontains=query)

        elif 'number' in self.request.GET:
            query = self.request.GET.get('number')
            return Book.objects.filter(user__id=self.request.user.id, number__icontains=query)

        elif 'price' in self.request.GET:
            query = self.request.GET.get('price')
            return Book.objects.filter(user__id=self.request.user.id,price=query)
        else:
            query = self.request.GET.get('stars')
            return Book.objects.filter(user__id=self.request.user.id, review__stars=query)

def new_book(request):
    if request.method == 'POST':
        book_form = BookForm(request.POST)
        review_form = ReviewForm(request.POST)
        if book_form.is_valid():
            book = book_form.save(commit=False)
            book.add_date = timezone.now()
            book.user = request.user
            book.save()
            review = review_form.save(commit=False)
            review.book = book
            review.save()
            return redirect('books:detail', pk=book.pk)       
    else:
        book_form = BookForm()
        review_form = ReviewForm()
    return render(request, 'books/book_edit.html', {
        'book_form': book_form,
        'review_form': review_form
    })

def update_book(request, book_id):
    instance = get_object_or_404(Book, id=book_id)
    form = BookForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            book = form.save()
            return redirect('books:detail', pk=book.pk)
    else:
        return render(request, 'books/book_edit.html', {'book_form': form, 'book_id': book_id})

def update_review(request, book_id):
    instance = get_object_or_404(Review, book=book_id)
    form = ReviewForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            review = form.save()
            return redirect('books:detail', pk=review.book.pk)
    else:
        return render(request, 'books/book_edit.html', {'review_form': form, 'book_id': book_id})

def delete_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    try:
        book.delete()
    except:
        print("Book not deleted successfully")
    else:
        return redirect('books:index')

books/templates/books/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="{% static 'base.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
  <meta name="google" content="notranslate" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

</head>

<body >
    <header class="mb-5 p-3 text-center">
    <h1 class="w3-jumbo"><b>شركة الدولية الحديثة</b></h1>
            <img src="dawlia.jpg"   height="200" width="200">

    </header>


    {% block recent %}{% endblock %}
    {% include 'books/search.html' %}
{#    <a href="/accounts/logout" class="float-right m-3">تسجيل خروج</a>#}
</body>

 <!-- bootstrap scripts -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>

</html>




<!DOCTYPE html>
<html lang="en">
<title>الدولية</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b>شركة الدولية<br> الحديثة</b></h3>
      <img src="dawlia.jpg"   height="200" width="200">
  </div>
  <div class="w3-bar-block" align="right">
      <a href="#" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">الرئيسية</a>
    <a href="{% url 'books:order_by' 'name' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">عرض حسب اسم الصنف</a>
    <a href="{% url 'books:order_by' 'company' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">حسب الشركة</a>
    <a href="{% url 'books:order_by' 'price' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">حسب السعر</a>
    <a href="{% url 'books:order_by' 'number' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">حسب رقم الصنف</a>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>شركة الدولية الحديثة</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>

  <!-- Photo grid (modal) -->
{#  <div class="w3-row-padding">#}
{#    <div class="w3-half">#}
{#      <img src="/w3images/kitchenconcrete.jpg" style="width:100%" onclick="onClick(this)" alt="Concrete meets bricks">#}
{#      <img src="/w3images/livingroom.jpg" style="width:100%" onclick="onClick(this)" alt="Light, white and tight scandinavian design">#}
{#      <img src="/w3images/diningroom.jpg" style="width:100%" onclick="onClick(this)" alt="White walls with designer chairs">#}
{#    </div>#}
{##}
{#    <div class="w3-half">#}
{#      <img src="/w3images/atrium.jpg" style="width:100%" onclick="onClick(this)" alt="Windows for the atrium">#}
{#      <img src="/w3images/bedroom.jpg" style="width:100%" onclick="onClick(this)" alt="Bedroom and office in one space">#}
{#      <img src="/w3images/livingroom2.jpg" style="width:100%" onclick="onClick(this)" alt="Scandinavian design">#}
{#    </div>#}
{#  </div>#}
{##}
{#  <!-- Modal for full size images on click-->#}
{#  <div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">#}
{#    <span class="w3-button w3-black w3-xxlarge w3-display-topright">×</span>#}
{#    <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">#}
{#      <img id="img01" class="w3-image">#}
{#      <p id="caption"></p>#}
{#    </div>#}
{#  </div>#}
{##}
{#  <!-- Services -->#}
{#  <div class="w3-container" id="services" style="margin-top:75px">#}
{#    <h1 class="w3-xxxlarge w3-text-red"><b>Services.</b></h1>#}
{#    <hr style="width:50px;border:5px solid red" class="w3-round">#}
{#    <p>We are a interior design service that focus on what's best for your home and what's best for you!</p>#}
{#    <p>Some text about our services - what we do and what we offer. We are lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure#}
{#    dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor#}
{#    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.#}
{#    </p>#}
{#  </div>#}
{##}
{#  <!-- Designers -->#}
{#  <div class="w3-container" id="designers" style="margin-top:75px">#}
{#    <h1 class="w3-xxxlarge w3-text-red"><b>Designers.</b></h1>#}
{#    <hr style="width:50px;border:5px solid red" class="w3-round">#}
{#    <p>The best team in the world.</p>#}
{#    <p>We are lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure#}
{#    dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor#}
{#    incididunt ut labore et quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.#}
{#    </p>#}
{#    <p><b>Our designers are thoughtfully chosen</b>:</p>#}
{#  </div>#}
{##}
{#  <!-- The Team -->#}
{#  <div class="w3-row-padding w3-grayscale">#}
{#    <div class="w3-col m4 w3-margin-bottom">#}
{#      <div class="w3-light-grey">#}
{#        <img src="/w3images/team2.jpg" alt="John" style="width:100%">#}
{#        <div class="w3-container">#}
{#          <h3>John Doe</h3>#}
{#          <p class="w3-opacity">CEO & Founder</p>#}
{#          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#    <div class="w3-col m4 w3-margin-bottom">#}
{#      <div class="w3-light-grey">#}
{#        <img src="/w3images/team1.jpg" alt="Jane" style="width:100%">#}
{#        <div class="w3-container">#}
{#          <h3>Jane Doe</h3>#}
{#          <p class="w3-opacity">Designer</p>#}
{#          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#    <div class="w3-col m4 w3-margin-bottom">#}
{#      <div class="w3-light-grey">#}
{#        <img src="/w3images/team3.jpg" alt="Mike" style="width:100%">#}
{#        <div class="w3-container">#}
{#          <h3>Mike Ross</h3>#}
{#          <p class="w3-opacity">Architect</p>#}
{#          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{##}
{#  <!-- Packages / Pricing Tables -->#}
{#  <div class="w3-container" id="packages" style="margin-top:75px">#}
{#    <h1 class="w3-xxxlarge w3-text-red"><b>Packages.</b></h1>#}
{#    <hr style="width:50px;border:5px solid red" class="w3-round">#}
{#    <p>Some text our prices. Lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure</p>#}
{#  </div>#}
{##}
{#  <div class="w3-row-padding">#}
{#    <div class="w3-half w3-margin-bottom">#}
{#      <ul class="w3-ul w3-light-grey w3-center">#}
{#        <li class="w3-dark-grey w3-xlarge w3-padding-32">Basic</li>#}
{#        <li class="w3-padding-16">Floorplanning</li>#}
{#        <li class="w3-padding-16">10 hours support</li>#}
{#        <li class="w3-padding-16">Photography</li>#}
{#        <li class="w3-padding-16">20% furniture discount</li>#}
{#        <li class="w3-padding-16">Good deals</li>#}
{#        <li class="w3-padding-16">#}
{#          <h2>$ 199</h2>#}
{#          <span class="w3-opacity">per room</span>#}
{#        </li>#}
{#        <li class="w3-light-grey w3-padding-24">#}
{#          <button class="w3-button w3-white w3-padding-large w3-hover-black">Sign Up</button>#}
{#        </li>#}
{#      </ul>#}
{#    </div>#}
{##}
{#    <div class="w3-half">#}
{#      <ul class="w3-ul w3-light-grey w3-center">#}
{#        <li class="w3-red w3-xlarge w3-padding-32">Pro</li>#}
{#        <li class="w3-padding-16">Floorplanning</li>#}
{#        <li class="w3-padding-16">50 hours support</li>#}
{#        <li class="w3-padding-16">Photography</li>#}
{#        <li class="w3-padding-16">50% furniture discount</li>#}
{#        <li class="w3-padding-16">GREAT deals</li>#}
{#        <li class="w3-padding-16">#}
{#          <h2>$ 249</h2>#}
{#          <span class="w3-opacity">per room</span>#}
{#        </li>#}
{#        <li class="w3-light-grey w3-padding-24">#}
{#          <button class="w3-button w3-red w3-padding-large w3-hover-black">Sign Up</button>#}
{#        </li>#}
{#      </ul>#}
{#    </div>#}
{#  </div>#}
{##}
{#  <!-- Contact -->#}
{#  <div class="w3-container" id="contact" style="margin-top:75px">#}
{#    <h1 class="w3-xxxlarge w3-text-red"><b>Contact.</b></h1>#}
{#    <hr style="width:50px;border:5px solid red" class="w3-round">#}
{#    <p>Do you want us to style your home? Fill out the form and fill me in with the details :) We love meeting new people!</p>#}
{#    <form action="/action_page.php" target="_blank">#}
{#      <div class="w3-section">#}
{#        <label>Name</label>#}
{#        <input class="w3-input w3-border" type="text" name="Name" required>#}
{#      </div>#}
{#      <div class="w3-section">#}
{#        <label>Email</label>#}
{#        <input class="w3-input w3-border" type="text" name="Email" required>#}
{#      </div>#}
{#      <div class="w3-section">#}
{#        <label>Message</label>#}
{#        <input class="w3-input w3-border" type="text" name="Message" required>#}
{#      </div>#}
{#      <button type="submit" class="w3-button w3-block w3-padding-large w3-red w3-margin-bottom">Send Message</button>#}
{#    </form>#}
{#  </div>#}
{##}
{#<!-- End page content -->#}
{#</div>#}

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

</body>
</html>

books/templates/books/book_view.html
{% extends 'books/base.html' %}

{#{% block recent %}#}
{#<div class="latest-wrapper container">#}
{#    <h5 class="mx-2 my-4 text-center">المضاف حديثا</h5>#}
{#    <div class="multiple-items">#}
{#        {% if books_list %}#}
{#        {% for book in books_list %}#}
{#        <div class="book-wrapper mx-2">#}
{#            {% if book.number %}#}
{#            <a href="{% url 'books:detail' book.id %}">#}
{#                <p>{{ book.number }}</p>#}
{#                                <p class="book-title">{{book.name}}</p>#}
{#            </a>#}
{#            {% endif %}#}
{#        </div>#}
{#        {% endfor %}#}
{#    </div>#}
{#    {% else %}#}
{#    <p>/</p>#}
{#    {% endif %}#}
{#    <div class="my-4 text-center">#}
{#        <a href="{% url 'books:new_book' %}">#}
{#            <button type="button" class="btn btn-secondary">اضافة صنف</button>#}
{#        </a>#}
{#    </div>#}
{#</div>#}
{##}
{#{% endblock %}#}

books/templates/books/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'books/style.css' %}">
    <script src="https://kit.fontawesome.com/4a3eda80d3.js" crossorigin="anonymous"></script>
    <title>{{ book.name }}</title>
</head>

<body>
    <div class="m-3">
        {% if error_message %}
        <p class="error">{{ error_message }}</p>
        {% endif %}
        <div class="book-header p-3">
            <h3 class="font-weight-bold">{{ book.name }}</h3>
            <h4 class="font-italic">by {{ book.company }}</h4>
        </div>

        {% if book.number %}
            <p2>{{ book.number }}</p2>
        {% endif %}

        <!-- Synopsis Section -->
        <div class="synopsis p-3">
            <p class="subtitle">price</p>
            {% if book.price %}
            <span>{{ book.price }}</span>
            {% else %}
            <span class="font-italic">لا توجد تفاصيل</span>
            {% endif %}
        </div>
        <!-- End Book Synopsis Section -->

        <!-- Book Review Section -->
        <div class="review p-3 my-3">
            <p class="subtitle baskerville">ملاحظة</p>
            <div class="mb-3">
                <span>{{ book.review.stars }}</span>
        </div>
        <p class="subtitle baskerville">تفاصيل</p>
        {% if book.review.thoughts %}
        <p>{{ book.review.thoughts }}</p>
        {% else %}
        <p class="font-italic">...</p>
        {% endif %}
        <a href="{% url 'books:update_review' book.id %}">
            <button class="btn btn-outline-secondary">تعديل التفاصيل</button>
        </a>
    </div>
    <!-- End Book Review Section -->

    <div class="edit-btns p-3 d-flex justify-content-between">
        <a href="{% url 'books:update_book' book.id %}">
            <button class="btn btn-info">تعديل الصنف</button>
        </a>
        <a href="{% url 'books:delete_book' book.id %}">
            <button class="btn btn-danger">حذف الصنف</button>
        </a>
    </div>
    <a class="p-3" href="{% url 'books:index' %}">رجوع للصفحة الرئيسية</a>
    </div>
</body>

</html>